//! `warren serve` — a loopback HTTP surface over the existing client core.
//!
//! This module owns **no protocol logic**. Every cryptographic and routing
//! step is delegated to the already-tested modules:
//!
//! - message bodies: [`crate::ratchet::RatchetClient::encrypt`] / `decrypt`
//! - admission proofs: [`crate::credential::ClientTokenWallet::spend_token`]
//! - path verification + transmit: [`crate::client::send_packet`]
//! - directory trust: [`crate::directory::SignedRelayList`] via `send_packet`
//! - delivery frames: [`crate::net::recv_frame`]
//!
//! What it *does* add is the two things a mixnet does not carry natively and
//! a message-bus consumer needs:
//!
//! 1. **A message id and a room label on the wire.** A caller that sends a
//!    message expects the receiver to report the *same* id, and to know which
//!    logical room it belonged to. Both ride inside the ratchet-encrypted
//!    body, so relays never see them.
//! 2. **Chunking.** A Sphinx payload holds [`crate::client::MAX_MSG_LEN`]
//!    (~705 B) of plaintext; bus payloads are routinely larger. Messages are
//!    split across packets and reassembled here. Each chunk is a separate
//!    packet and therefore **spends one admission token**.
//!
//! Ordering is best-effort by construction: Poisson per-hop mix delays
//! reorder packets on purpose, so a monotonic per-sender counter plus a short
//! reorder window ([`REORDER_WINDOW`]) restores FIFO when it can and releases
//! out of order rather than stalling when it cannot.
//!
//! The server binds loopback only — see [`serve`].

use std::collections::{BTreeMap, HashMap, VecDeque};
use std::io::Write;
use std::net::{Ipv4Addr, SocketAddr, TcpListener};
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::mpsc::{Receiver, RecvTimeoutError, Sender, channel};
use std::sync::{Arc, Mutex};
use std::time::{Duration, Instant, SystemTime, UNIX_EPOCH};

use anyhow::{Context, Result, anyhow};
use serde::{Deserialize, Serialize};
use serde_json::{Value, json};
use tiny_http::{Header, Method, Request, Response, Server};

use sha2::{Digest, Sha256};

use crate::client::{self, MAX_MSG_LEN};
use crate::config::Config;
use crate::credential::{self, ClientTokenWallet, Epoch, Issuer};
use crate::directory::SignedRelayList;
use crate::net;
use crate::ratchet::RatchetClient;

/// How long a completed message waits for an earlier-numbered sibling before
/// it is released out of order. Mix delays are milliseconds-to-seconds, so
/// this trades a small latency floor for FIFO in the common case.
pub const REORDER_WINDOW: Duration = Duration::from_millis(1500);

/// Partial reassembly buffers older than this are dropped, so a permanently
/// lost chunk cannot pin memory forever.
const PARTIAL_TTL: Duration = Duration::from_secs(120);

/// One wire frame: a chunk of one logical message, carried as the ratchet
/// plaintext. Keys are single letters because every byte competes with the
/// payload budget.
#[derive(Debug, Clone, Serialize, Deserialize)]
struct WireFrame {
    /// Message id, generated by the sender and reported unchanged by the
    /// receiver.
    m: String,
    /// Monotonic per-sender counter, used to restore send order.
    c: u64,
    /// Chunk index.
    s: u32,
    /// Total chunk count.
    n: u32,
    /// Logical room label.
    r: String,
    /// Hex-encoded slice of the message body. Hex (not raw text) so that
    /// reassembly is byte-exact regardless of JSON escaping and so chunk
    /// boundaries never split a UTF-8 sequence.
    d: String,
}

/// A message that has been fully reassembled and is ready to hand out.
#[derive(Debug, Clone)]
struct Ready {
    id: String,
    room: String,
    sender: String,
    content: String,
    /// How many packets it arrived in.
    chunks: u32,
}

#[derive(Debug)]
struct Partial {
    total: u32,
    room: String,
    sender: String,
    counter: u64,
    chunks: BTreeMap<u32, String>,
    first_seen: Instant,
}

/// Reassembly, reordering and ack bookkeeping for delivered messages.
#[derive(Debug, Default)]
struct Inbox {
    partial: HashMap<String, Partial>,
    /// Complete but not yet released, awaiting their turn in counter order.
    holding: Vec<(Ready, u64, Instant)>,
    /// Next counter expected from each sender. Absent until the reorder
    /// window closes on that sender's first batch — the first packet to
    /// *arrive* is often not the first one *sent*, so the baseline cannot be
    /// taken from it.
    next_expect: HashMap<String, u64>,
    /// Released, in order, waiting to be polled.
    ready: VecDeque<Ready>,
    /// The same releases, for the UI journal. A separate queue because the
    /// journal must see every message even though `ready` is consumed by
    /// whichever client polls first.
    journal: VecDeque<Ready>,
    /// Ack transitions in the order they were recorded, for observability.
    acks: Vec<(String, String)>,
}

impl Inbox {
    /// Feed one decrypted frame. Returns once the frame is stored; released
    /// messages land in `ready`.
    fn accept(&mut self, sender: String, frame: WireFrame) {
        self.expire_partials();

        if frame.n == 0 || frame.s >= frame.n {
            return; // malformed; drop rather than allocate on attacker input
        }

        let entry = self
            .partial
            .entry(frame.m.clone())
            .or_insert_with(|| Partial {
                total: frame.n,
                room: frame.r.clone(),
                sender: sender.clone(),
                counter: frame.c,
                chunks: BTreeMap::new(),
                first_seen: Instant::now(),
            });
        entry.chunks.insert(frame.s, frame.d);

        if entry.chunks.len() as u32 != entry.total {
            return;
        }

        let done = self
            .partial
            .remove(&frame.m)
            .expect("just checked complete");
        let hex_body: String = done.chunks.into_values().collect();
        let Ok(bytes) = hex::decode(&hex_body) else {
            return;
        };
        let Ok(content) = String::from_utf8(bytes) else {
            return;
        };

        self.holding.push((
            Ready {
                id: frame.m,
                room: done.room,
                sender: done.sender,
                content,
                chunks: done.total,
            },
            done.counter,
            Instant::now(),
        ));
        self.release();
    }

    /// Move holding messages into `ready` in per-sender counter order.
    ///
    /// Three rules, in priority order:
    /// 1. A message whose counter is *below* what we already released is a
    ///    late arrival — hand it over immediately rather than strand it, and
    ///    leave the expectation where it is.
    /// 2. A message that is exactly the next expected counter is released and
    ///    advances the expectation.
    /// 3. Otherwise there is a gap — either a genuine hole, or a sender we
    ///    have not seen before. Wait [`REORDER_WINDOW`], then release the
    ///    lowest counter held for that sender and resync onto it. This is
    ///    what makes the *first* batch from a sender come out in send order:
    ///    the earliest counter usually lands inside the window even when it
    ///    is not the first to arrive.
    fn release(&mut self) {
        loop {
            let mut moved = false;

            let mut i = 0;
            while i < self.holding.len() {
                let (ready, counter, _) = &self.holding[i];
                match self.next_expect.get(&ready.sender).copied() {
                    Some(expected) if *counter < expected => {
                        let (ready, _, _) = self.holding.remove(i);
                        self.ready.push_back(ready.clone());
                        self.journal.push_back(ready);
                        moved = true;
                    }
                    Some(expected) if *counter == expected => {
                        let (ready, counter, _) = self.holding.remove(i);
                        self.next_expect.insert(ready.sender.clone(), counter + 1);
                        self.ready.push_back(ready.clone());
                        self.journal.push_back(ready);
                        moved = true;
                    }
                    _ => i += 1,
                }
            }
            if moved {
                continue;
            }

            // Nothing fit in order: if a waiter has sat out the window,
            // release the lowest counter for its sender and resync onto it.
            let stale = self
                .holding
                .iter()
                .enumerate()
                .filter(|(_, (_, _, at))| at.elapsed() >= REORDER_WINDOW)
                .min_by(|(_, (ra, ca, _)), (_, (rb, cb, _))| {
                    (&ra.sender, ca).cmp(&(&rb.sender, cb))
                })
                .map(|(i, _)| i);

            match stale {
                Some(i) => {
                    let (ready, counter, _) = self.holding.remove(i);
                    self.next_expect.insert(ready.sender.clone(), counter + 1);
                    self.ready.push_back(ready.clone());
                    self.journal.push_back(ready);
                }
                None => break,
            }
        }
    }

    fn expire_partials(&mut self) {
        self.partial
            .retain(|_, p| p.first_seen.elapsed() < PARTIAL_TTL);
    }

    /// Pop the next released message, running the reorder pass first so a
    /// gap that has timed out is not held past its window.
    fn pop(&mut self) -> Option<Ready> {
        self.release();
        self.ready.pop_front()
    }

    /// Take everything released since the last call, for the UI journal.
    /// Independent of [`Inbox::pop`], which serves API consumers.
    fn drain_released(&mut self) -> Vec<Ready> {
        self.release();
        self.journal.drain(..).collect()
    }

    fn ack(&mut self, id: &str, state: &str) {
        self.acks.push((id.to_string(), state.to_string()));
    }
}

/// Wall-clock milliseconds. The UI formats timestamps itself, so the wire
/// carries epoch millis rather than a formatted date — no date dependency.
fn now_ms() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_millis() as u64)
        .unwrap_or(0)
}

/// How many messages and events the daemon keeps for the UI. This is a live
/// view, not an archive: the ledger of record is the wallet + ratchet state on
/// disk, and deliberately *not* a log of who talked to whom.
const HISTORY_LIMIT: usize = 200;
const EVENT_LIMIT: usize = 500;

/// Request-handling threads. Each open SSE stream occupies one for as long as
/// the browser tab lives, so this is "a few UI tabs plus headroom", not a
/// throughput setting.
const SERVER_THREADS: usize = 8;

/// Heartbeat cadence for the SSE stream, matching what browsers and proxies
/// expect before they consider an idle connection dead.
const SSE_KEEPALIVE: Duration = Duration::from_secs(15);

/// One hop of a message's journey.
///
/// On the **send** side these are real and verifiable: the path was checked
/// against the signed relay list and each relay's live self-signed claim
/// before the packet went out, so the address and identity key here are the
/// ones the packet was actually built for.
///
/// On the **receive** side there are none, and that is the system working: a
/// recipient learns nothing about the path a message took.
#[derive(Debug, Clone, Serialize)]
struct HopRecord {
    index: usize,
    role: &'static str,
    addr: String,
    identity_key: String,
    sphinx_key: String,
}

/// A message as the UI sees it — one row in the trace, one card on the desk.
#[derive(Debug, Clone, Serialize)]
struct MessageRecord {
    id: String,
    peer: String,
    room: String,
    /// `sent` or `recv`.
    direction: &'static str,
    state: &'static str,
    bytes: usize,
    chunks: u32,
    /// Tokens spent on this message — one per packet, so this is `chunks` on
    /// the send side and 0 on the receive side.
    tokens_spent: u32,
    /// SHA-256 over the concatenated ciphertext actually put on the wire.
    /// Verifiable, and the closest honest analogue of an audit leaf.
    sha256: String,
    hops: Vec<HopRecord>,
    preview: String,
    error: Option<String>,
    created_at: u64,
    updated_at: u64,
}

/// One line in the live wire trace the UI streams over SSE.
#[derive(Debug, Clone, Serialize)]
struct WireEvent {
    ts: u64,
    /// Which topology node this concerns: `sender`, `entry`, `middle`, `exit`,
    /// `recipient`, `directory`, `issuer`.
    node: &'static str,
    /// `encrypt`, `token`, `sphinx`, `deliver`, `decrypt`, `reassemble`,
    /// `directory`, `error`.
    kind: &'static str,
    direction: &'static str,
    msg_id: String,
    peer: String,
    room: String,
    state: &'static str,
    detail: String,
}

/// Fan-out of [`WireEvent`]s to connected SSE clients, plus a bounded replay
/// buffer so a page load starts with context instead of a blank panel.
#[derive(Debug, Default)]
struct EventHub {
    recent: VecDeque<String>,
    subscribers: Vec<Sender<String>>,
}

impl EventHub {
    fn publish(&mut self, event: &WireEvent) {
        let Ok(json) = serde_json::to_string(event) else {
            return;
        };
        self.recent.push_back(json.clone());
        while self.recent.len() > EVENT_LIMIT {
            self.recent.pop_front();
        }
        // Drop subscribers whose reader has gone away.
        self.subscribers.retain(|tx| tx.send(json.clone()).is_ok());
    }

    fn subscribe(&mut self) -> Receiver<String> {
        let (tx, rx) = channel();
        for past in &self.recent {
            let _ = tx.send(past.clone());
        }
        self.subscribers.push(tx);
        rx
    }
}

/// Everything a request handler needs.
///
/// `config`/`list` are a **startup snapshot for the UI endpoints only**. The
/// send path deliberately re-reads config, relay list, wallet and ratchet
/// from disk on every send — exactly like the one-shot CLI [`client::send`]
/// re-reads them on every invocation. A daemon that spends from
/// startup-loaded memory silently diverges from the CLI the moment anything
/// on disk changes (a re-issued token batch, an edited peer list, a
/// re-fetched relay list): the CLI keeps working while `/send` fails with a
/// stale "out of tokens" or "unknown peer".
struct ServeState {
    home: PathBuf,
    /// Config + relay-list paths, so every send can re-read them from disk
    /// (CLI parity).
    config_path: PathBuf,
    relays_path: PathBuf,
    config: Config,
    list: SignedRelayList,
    inbox: Mutex<Inbox>,
    counter: AtomicU64,
    listen_addr: String,
    /// Live view of recent traffic, for the UI. Bounded, in memory, never
    /// written to disk.
    messages: Mutex<VecDeque<MessageRecord>>,
    events: Mutex<EventHub>,
}

impl ServeState {
    fn load(
        home: &Path,
        config_path: &Path,
        relays_path: &Path,
        listen_addr: &str,
    ) -> Result<Self> {
        let config = Config::load(config_path)?;
        let list = SignedRelayList::load_and_verify(relays_path)?;
        // Startup guards only — the CLI re-checks both on every invocation,
        // and so does the send path below; these one-time checks just fail
        // fast with the same guidance instead of letting every send error
        // later. Nothing here becomes live state.
        RatchetClient::load(home).context("no ratchet state — run `warren ratchet-init` first")?;
        let wallet_path = home.join("wallet.json");
        ClientTokenWallet::load(&wallet_path).with_context(|| {
            format!(
                "no token wallet at `{}` — run `warren token-issue` first",
                wallet_path.display()
            )
        })?;
        Ok(Self {
            home: home.to_path_buf(),
            config_path: config_path.to_path_buf(),
            relays_path: relays_path.to_path_buf(),
            config,
            list,
            inbox: Mutex::new(Inbox::default()),
            counter: AtomicU64::new(0),
            listen_addr: listen_addr.to_string(),
            messages: Mutex::new(VecDeque::new()),
            events: Mutex::new(EventHub::default()),
        })
    }

    /// The 3-hop path this client sends over, resolved against the signed
    /// relay list so the keys shown are the ones the packet is built for.
    /// Takes the *fresh* config + list the send was built against, never the
    /// startup snapshot.
    fn hops(&self, config: &Config, list: &SignedRelayList) -> Vec<HopRecord> {
        const ROLES: [&str; 3] = ["entry", "middle", "exit"];
        config
            .relays
            .path()
            .iter()
            .zip(ROLES)
            .enumerate()
            .map(|(index, (addr, role))| {
                let claim = list.get(addr);
                HopRecord {
                    index,
                    role,
                    addr: (*addr).to_string(),
                    identity_key: claim
                        .map(|c| hex::encode(c.identity_pubkey))
                        .unwrap_or_default(),
                    sphinx_key: claim
                        .map(|c| hex::encode(c.sphinx_pubkey))
                        .unwrap_or_default(),
                }
            })
            .collect()
    }

    fn emit(&self, event: WireEvent) {
        self.events
            .lock()
            .expect("event mutex poisoned")
            .publish(&event);
    }

    fn record(&self, message: MessageRecord) {
        let mut messages = self.messages.lock().expect("message mutex poisoned");
        messages.push_front(message);
        while messages.len() > HISTORY_LIMIT {
            messages.pop_back();
        }
    }

    /// Record and announce messages that have just been released.
    fn journal(&self, released: Vec<Ready>) {
        for msg in released {
            let now = now_ms();
            self.record(MessageRecord {
                id: msg.id.clone(),
                peer: short_key(&msg.sender),
                room: msg.room.clone(),
                direction: "recv",
                state: "DELIVERED",
                bytes: msg.content.len(),
                chunks: msg.chunks,
                tokens_spent: 0,
                sha256: String::new(),
                // Deliberately empty: a recipient cannot see the path a
                // message took. That absence is the anonymity property.
                hops: Vec::new(),
                preview: preview_of(&msg.content),
                error: None,
                created_at: now,
                updated_at: now,
            });
            self.emit(WireEvent {
                ts: now,
                node: "recipient",
                kind: "reassemble",
                direction: "in",
                msg_id: msg.id,
                peer: short_key(&msg.sender),
                room: msg.room,
                state: "DELIVERED",
                detail: format!(
                    "{} B reassembled from {} packet(s); path unknown to the receiver",
                    msg.content.len(),
                    msg.chunks
                ),
            });
        }
    }

    /// Release anything whose reorder window has closed and journal it.
    ///
    /// The receiver thread only runs when a packet arrives, but the reorder
    /// window closes on a timer — so the last message of a burst would never
    /// be journaled if this were not also driven by incoming requests.
    fn harvest(&self) {
        let released = self
            .inbox
            .lock()
            .expect("inbox mutex poisoned")
            .drain_released();
        if !released.is_empty() {
            self.journal(released);
        }
    }

    /// Update the newest record with this id, if it is still in the window.
    fn update<F: FnOnce(&mut MessageRecord)>(&self, id: &str, apply: F) {
        let mut messages = self.messages.lock().expect("message mutex poisoned");
        if let Some(m) = messages.iter_mut().find(|m| m.id == id) {
            apply(m);
            m.updated_at = now_ms();
        }
    }

    /// Split `content` into wire frames, then encrypt-spend-transmit each one
    /// through the existing send path. Returns the message id.
    ///
    /// Each stage is narrated onto the event stream as it happens, so the UI
    /// shows the real sequence — encrypt, spend a token, push into the entry
    /// relay — rather than a spinner and a result.
    fn send_message(&self, room: &str, peer_label: &str, content: &str) -> Result<String> {
        // CLI parity (see [`client::send`]): config, the signed relay list,
        // the ratchet and the wallet are re-read from disk on every send,
        // exactly like the one-shot CLI re-reads them on every invocation. A
        // token batch re-issued while serve runs, a peer added to (or removed
        // from) the config, or a re-fetched relay list must be honored by the
        // next send — otherwise `/send` diverges from `warren send` and fails
        // with a stale in-memory "out of tokens"/"unknown peer" while the
        // CLI keeps working.
        let config = Config::load(&self.config_path)?;
        let list = SignedRelayList::load_and_verify(&self.relays_path)?;
        let peer = config.peers.get(peer_label).ok_or_else(|| {
            anyhow!("unknown peer `{peer_label}` — add it under [peers] in the config")
        })?;
        let mut ratchet = RatchetClient::load(&self.home)?;
        let mut wallet = ClientTokenWallet::load(&self.home.join("wallet.json"))?;

        let id = self.new_message_id();
        let counter = self.counter.fetch_add(1, Ordering::SeqCst);
        let frames = build_frames(&id, counter, room, content)?;
        let now = now_ms();

        self.record(MessageRecord {
            id: id.clone(),
            peer: peer_label.to_string(),
            room: room.to_string(),
            direction: "sent",
            state: "QUEUED",
            bytes: content.len(),
            chunks: frames.len() as u32,
            tokens_spent: 0,
            sha256: String::new(),
            hops: self.hops(&config, &list),
            preview: preview_of(content),
            error: None,
            created_at: now,
            updated_at: now,
        });
        self.emit(WireEvent {
            ts: now,
            node: "sender",
            kind: "encrypt",
            direction: "out",
            msg_id: id.clone(),
            peer: peer_label.to_string(),
            room: room.to_string(),
            state: "QUEUED",
            detail: format!(
                "{} B split into {} packet(s) of at most {MAX_MSG_LEN} B",
                content.len(),
                frames.len()
            ),
        });

        let mut digest = Sha256::new();
        let mut spent = 0u32;

        for (i, frame) in frames.iter().enumerate() {
            let plaintext = serde_json::to_string(frame)?;
            let wire = ratchet.encrypt(&peer.id, &peer.otk, &plaintext)?;
            digest.update(&wire);

            let token = match wallet.spend_token() {
                Ok(token) => token,
                Err(e) => {
                    self.fail(&id, peer_label, room, &e.to_string(), spent);
                    return Err(e);
                }
            };
            wallet.save(&self.home.join("wallet.json"))?;
            spent += 1;
            self.emit(WireEvent {
                ts: now_ms(),
                node: "issuer",
                kind: "token",
                direction: "out",
                msg_id: id.clone(),
                peer: peer_label.to_string(),
                room: room.to_string(),
                state: "ENCRYPTED",
                detail: format!(
                    "packet {}/{}: spent admission token {} (epoch {})",
                    i + 1,
                    frames.len(),
                    &hex::encode(token.id())[..12],
                    token.epoch.0
                ),
            });

            if let Err(e) = client::send_packet(&config, &list, &peer.addr, &wire, Some(&token)) {
                self.fail(&id, peer_label, room, &format!("{e:#}"), spent);
                return Err(e);
            }
            self.emit(WireEvent {
                ts: now_ms(),
                node: "entry",
                kind: "sphinx",
                direction: "out",
                msg_id: id.clone(),
                peer: peer_label.to_string(),
                room: room.to_string(),
                state: "IN_FLIGHT",
                detail: format!(
                    "packet {}/{} pushed into {} → {} → {}",
                    i + 1,
                    frames.len(),
                    self.config.relays.entry,
                    self.config.relays.middle,
                    self.config.relays.exit
                ),
            });
        }

        let sha = hex::encode(digest.finalize());
        self.update(&id, |m| {
            m.state = "IN_FLIGHT";
            m.tokens_spent = spent;
            m.sha256 = sha.clone();
        });
        self.emit(WireEvent {
            ts: now_ms(),
            node: "exit",
            kind: "deliver",
            direction: "out",
            msg_id: id.clone(),
            peer: peer_label.to_string(),
            room: room.to_string(),
            state: "IN_FLIGHT",
            // The sender genuinely cannot observe the delivery — the exit
            // relay hands off to the recipient with no acknowledgement back
            // along the path. Saying so is more honest than a fake tick.
            detail: "handed to the mix path; delivery is unacknowledged by design".into(),
        });
        Ok(id)
    }

    /// Mark a send as failed and say why, on both the record and the stream.
    fn fail(&self, id: &str, peer: &str, room: &str, error: &str, spent: u32) {
        let reason = error.to_string();
        self.update(id, |m| {
            m.state = "FAILED";
            m.tokens_spent = spent;
            m.error = Some(reason.clone());
        });
        self.emit(WireEvent {
            ts: now_ms(),
            node: "sender",
            kind: "error",
            direction: "out",
            msg_id: id.to_string(),
            peer: peer.to_string(),
            room: room.to_string(),
            state: "FAILED",
            detail: error.to_string(),
        });
    }

    /// Our Layer-3 identity (hex), read fresh like the rest of the send path:
    /// the account identity is stable, but there is no reason to trust a
    /// startup snapshot for it. A missing account (deleted mid-run) yields an
    /// empty string rather than failing the request — message ids degrade to
    /// `wb-…` and the UI shows an empty identity, which is honest noise on a
    /// broken setup.
    fn identity_hex(&self) -> String {
        RatchetClient::load(&self.home)
            .map(|r| r.identity_hex())
            .unwrap_or_default()
    }

    /// Message ids must be unique per sender and are only ever compared for
    /// equality, so the ratchet identity plus a counter and the wall clock is
    /// enough — no extra dependency for a UUID.
    fn new_message_id(&self) -> String {
        let identity = self.identity_hex();
        let nanos = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_nanos())
            .unwrap_or(0);
        let seq = self.counter.load(Ordering::SeqCst);
        format!("wb-{}-{nanos:x}-{seq:x}", &identity[..8])
    }

    fn token_count(&self) -> usize {
        // Fresh read from disk, so the UI never shows a startup-stale count
        // after a re-issue or a CLI send while the daemon runs.
        ClientTokenWallet::load(&self.home.join("wallet.json"))
            .map(|w| w.token_count())
            .unwrap_or(0)
    }
}

/// A short, single-line excerpt for list rows. Full bodies stay out of the
/// summary endpoints.
fn preview_of(content: &str) -> String {
    let flat: String = content
        .chars()
        .map(|c| if c.is_control() { ' ' } else { c })
        .collect();
    let trimmed = flat.trim();
    match trimmed.char_indices().nth(140) {
        Some((cut, _)) => format!("{}…", &trimmed[..cut]),
        None => trimmed.to_string(),
    }
}

/// How many hex characters of body fit in one frame once the envelope is
/// serialized. Measured with worst-case chunk indices so a frame can never grow
/// past the budget as `n` gains digits.
fn hex_budget(id: &str, counter: u64, room: &str) -> Result<usize> {
    let probe = WireFrame {
        m: id.to_string(),
        c: counter,
        s: u32::MAX,
        n: u32::MAX,
        r: room.to_string(),
        d: String::new(),
    };
    let overhead = serde_json::to_string(&probe)?.len();
    Ok(MAX_MSG_LEN
        .checked_sub(overhead)
        .filter(|b| *b >= 2)
        .ok_or_else(|| {
            anyhow!("room label `{room}` leaves no room for payload inside a Sphinx packet")
        })?
        & !1) // even, so each chunk is a whole number of bytes
}

/// Body bytes that fit in one packet. Half the hex budget, because the body
/// travels hex-encoded — the number a caller needs to predict how many packets
/// (and therefore how many admission tokens) a message will cost.
fn packet_payload_bytes(room: &str) -> usize {
    // A representative id: they are a fixed shape, so this is exact in practice.
    hex_budget("wb-00000000-0000000000000000-0", 0, room).unwrap_or(0) / 2
}

/// Split a body into frames that each fit inside [`MAX_MSG_LEN`] once
/// serialized. The body travels hex-encoded, so the per-frame budget is
/// measured in hex characters and kept even to preserve byte alignment.
fn build_frames(id: &str, counter: u64, room: &str, content: &str) -> Result<Vec<WireFrame>> {
    let hex_body = hex::encode(content.as_bytes());
    let budget = hex_budget(id, counter, room)?;

    let chunks: Vec<String> = if hex_body.is_empty() {
        vec![String::new()]
    } else {
        hex_body
            .as_bytes()
            .chunks(budget)
            .map(|c| String::from_utf8_lossy(c).into_owned())
            .collect()
    };

    let total = chunks.len() as u32;
    Ok(chunks
        .into_iter()
        .enumerate()
        .map(|(i, d)| WireFrame {
            m: id.to_string(),
            c: counter,
            s: i as u32,
            n: total,
            r: room.to_string(),
            d,
        })
        .collect())
}

/// Accept loop for messages the exit relay delivers to this client. Mirrors
/// [`client::listen`], but feeds the inbox instead of printing — the frame
/// handling and decryption are the same public calls.
fn spawn_receiver(state: Arc<ServeState>) -> Result<()> {
    let listener = TcpListener::bind(&state.listen_addr)
        .with_context(|| format!("cannot bind delivery address `{}`", state.listen_addr))?;
    std::thread::spawn(move || {
        for stream in listener.incoming() {
            let mut stream = match stream {
                Ok(s) => s,
                Err(_) => continue,
            };
            let Ok(Some((net::FRAME_DELIVER, body))) = net::recv_frame(&mut stream) else {
                continue;
            };
            // CLI parity on the receive side too: re-read the ratchet from
            // disk per delivery so sessions advanced by the CLI (or another
            // process) while serve runs are honored — a startup snapshot
            // would reject every message sent after it was taken.
            let decrypted = match RatchetClient::load(&state.home) {
                Ok(mut ratchet) => ratchet.decrypt(&body),
                Err(_) => {
                    state.emit(WireEvent {
                        ts: now_ms(),
                        node: "recipient",
                        kind: "error",
                        direction: "in",
                        msg_id: String::new(),
                        peer: String::new(),
                        room: String::new(),
                        state: "FAILED",
                        detail: "no ratchet state for delivery".into(),
                    });
                    continue;
                }
            };
            let Ok((sender, plaintext)) = decrypted else {
                state.emit(WireEvent {
                    ts: now_ms(),
                    node: "recipient",
                    kind: "error",
                    direction: "in",
                    msg_id: String::new(),
                    peer: String::new(),
                    room: String::new(),
                    state: "FAILED",
                    detail: "undecryptable delivery dropped".into(),
                });
                continue; // same disposition as the CLI listener
            };
            let Ok(frame) = serde_json::from_slice::<WireFrame>(&plaintext) else {
                continue; // not a serve-framed message
            };

            let short = short_key(&sender);
            state.emit(WireEvent {
                ts: now_ms(),
                node: "recipient",
                kind: "decrypt",
                direction: "in",
                msg_id: frame.m.clone(),
                peer: short.clone(),
                room: frame.r.clone(),
                state: "IN_FLIGHT",
                detail: format!("packet {}/{} decrypted from {short}", frame.s + 1, frame.n),
            });

            let released = {
                let mut inbox = state.inbox.lock().expect("inbox mutex poisoned");
                inbox.accept(sender, frame);
                inbox.drain_released()
            };
            state.journal(released);
        }
    });
    Ok(())
}

/// Identity keys are 64 hex characters; the UI shows a stable short form.
fn short_key(key: &str) -> String {
    key.chars().take(12).collect()
}

/// Token issuance, shared by the `token-issue` subcommand and the HTTP
/// endpoint so the issuer/PoW/wallet sequence exists in exactly one place.
///
/// Local dev-tool issuance: plays both issuer and client roles. Bootstrap
/// (M6): the client mines a proof of work over the issuer's per-request
/// challenge (bound to client-id + epoch) before the batch is granted — the
/// cost that makes mass identity-minting expensive (spec §4/§9; see
/// `docs/THREAT_MODEL.md` §3.2 and `docs/SPAM_RESISTANCE.md` §3).
pub fn token_issue(
    count: usize,
    epoch: Option<Epoch>,
    pow_bits: u32,
    client_id: &str,
    home: &Path,
) -> Result<String> {
    let epoch = epoch.unwrap_or_else(Epoch::now);
    // Reuse the persisted issuer key so re-running `token-issue` does not
    // silently invalidate relays already configured with `--admit-key`.
    let mut issuer = Issuer::load_or_new(Some(&home.join("issuer.pem")), epoch)?;
    issuer.set_pow_bits(pow_bits)?;

    let challenge = issuer.pow_challenge(client_id, epoch)?;
    let counter = crate::pow::mine(&challenge, pow_bits);
    issuer.grant_batch(client_id, epoch, counter)?;

    let mut wallet = ClientTokenWallet::new(epoch, issuer.public_key_pem()?);
    wallet.request_batch(&issuer, count)?;
    let hashes = counter + 1;

    wallet.save(&home.join("wallet.json"))?;
    // Persist the issuer keypair so relays can be configured with --admit-key
    // and so a later epoch can re-issue (M-later).
    credential::write_private(
        &home.join("issuer.pem"),
        issuer.private_key_pem()?.as_bytes(),
    )?;
    credential::write_private(
        &home.join("issuer.pub"),
        issuer.public_key_pem()?.as_bytes(),
    )?;

    Ok(format!(
        "issued {count} admission tokens for epoch {} to `{client_id}` (proof of work: \
         {pow_bits}-bit difficulty, {hashes} hashes) → {}",
        epoch.0,
        home.join("wallet.json").display()
    ))
}

/// Run the loopback API server. `port` is bound on 127.0.0.1 only — the
/// address is not configurable, because this surface holds an unlocked
/// wallet and ratchet and has no authentication of its own.
pub fn serve(
    port: u16,
    listen_addr: &str,
    home: &Path,
    config_path: &Path,
    relays_path: &Path,
) -> Result<String> {
    require_loopback(listen_addr)?;

    let state = Arc::new(ServeState::load(
        home,
        config_path,
        relays_path,
        listen_addr,
    )?);
    spawn_receiver(Arc::clone(&state))?;

    let bind = SocketAddr::from((Ipv4Addr::LOCALHOST, port));
    let server = Server::http(bind).map_err(|e| anyhow!("cannot bind {bind}: {e}"))?;
    println!(
        "warren serve on http://{} (deliveries on {}, {} tokens)",
        server.server_addr(),
        listen_addr,
        state.token_count()
    );

    // A small pool, because `/api/v1/stream` holds its thread for the life of
    // the connection. A single-threaded accept loop would let one open UI tab
    // block every other request.
    let server = Arc::new(server);
    let mut workers = Vec::new();
    for _ in 0..SERVER_THREADS {
        let server = Arc::clone(&server);
        let state = Arc::clone(&state);
        workers.push(std::thread::spawn(move || {
            while let Ok(request) = server.recv() {
                handle(&state, request);
            }
        }));
    }
    for worker in workers {
        let _ = worker.join();
    }
    Ok("serve stopped".into())
}

/// The delivery listener must also stay on loopback: it terminates the
/// mixnet path and hands plaintext to the ratchet.
fn require_loopback(addr: &str) -> Result<()> {
    let parsed: SocketAddr = addr
        .parse()
        .with_context(|| format!("cannot parse delivery address `{addr}`"))?;
    if !parsed.ip().is_loopback() {
        anyhow::bail!("`warren serve` only binds loopback; `{addr}` is not a loopback address");
    }
    Ok(())
}

fn handle(state: &Arc<ServeState>, mut request: Request) {
    let method = request.method().clone();
    let url = request.url().to_string();
    let path = url.split('?').next().unwrap_or("").to_string();
    let query = url.split_once('?').map(|(_, q)| q.to_string());
    let segments: Vec<&str> = path.trim_matches('/').split('/').collect();

    // The dev UI runs on its own port, so every response carries CORS headers
    // and a preflight is answered without touching any state.
    if matches!(method, Method::Options) {
        let mut response = Response::from_string(String::new()).with_status_code(204);
        for header in cors_headers() {
            response.add_header(header);
        }
        let _ = request.respond(response);
        return;
    }

    // The event stream is not a JSON reply: it holds the connection open and
    // writes frames as they happen.
    if matches!(method, Method::Get) && segments == ["api", "v1", "stream"] {
        stream_events(state, request, query.as_deref());
        return;
    }

    let mut body = String::new();
    if matches!(method, Method::Post) {
        let _ = request.as_reader().read_to_string(&mut body);
    }

    let (status, payload) = route(state, &method, &segments, &body);
    let mut response = match payload {
        Some(value) => Response::from_string(value.to_string())
            .with_status_code(status)
            .with_header(json_header()),
        None => Response::from_string(String::new()).with_status_code(status),
    };
    for header in cors_headers() {
        response.add_header(header);
    }
    let _ = request.respond(response);
}

fn json_header() -> Header {
    Header::from_bytes(&b"Content-Type"[..], &b"application/json"[..])
        .expect("static header is valid")
}

/// The API is loopback-only, so the browser's origin check is not the security
/// boundary here — the bind address is. These headers exist so the Next.js dev
/// server on another localhost port can talk to the daemon at all.
fn cors_headers() -> Vec<Header> {
    [
        ("Access-Control-Allow-Origin", "*"),
        ("Access-Control-Allow-Methods", "GET, POST, OPTIONS"),
        ("Access-Control-Allow-Headers", "Content-Type"),
    ]
    .iter()
    .filter_map(|(k, v)| Header::from_bytes(k.as_bytes(), v.as_bytes()).ok())
    .collect()
}

/// Serve the SSE stream by writing the response directly to the socket.
///
/// `Response` is not usable here: it buffers the body and only flushes when
/// the reader is exhausted, which for an endless stream is never — the client
/// receives nothing at all. Taking the writer lets each event be flushed the
/// moment it is published, which is the entire point of the endpoint.
fn stream_events(state: &Arc<ServeState>, request: Request, query: Option<&str>) {
    // `?replay=0` opts out of the buffered backlog and starts from now.
    let replay = !matches!(query, Some(q) if q.contains("replay=0"));
    let rx = {
        let mut hub = state.events.lock().expect("event mutex poisoned");
        let rx = hub.subscribe();
        if !replay {
            // Drop whatever `subscribe` pre-loaded.
            while rx.try_recv().is_ok() {}
        }
        rx
    };

    let mut writer = request.into_writer();
    // `Connection: close` and no Content-Length: the body runs until the
    // socket does. `EventSource` handles that shape natively.
    let head = concat!(
        "HTTP/1.1 200 OK\r\n",
        "Content-Type: text/event-stream\r\n",
        "Cache-Control: no-cache\r\n",
        "Connection: close\r\n",
        "Access-Control-Allow-Origin: *\r\n",
        "\r\n",
        // An opening comment flushes the headers, so the browser reports the
        // stream as open rather than pending.
        ": warren event stream\n\n",
    );
    if writer.write_all(head.as_bytes()).is_err() || writer.flush().is_err() {
        return;
    }

    loop {
        let frame = match rx.recv_timeout(SSE_KEEPALIVE) {
            Ok(json) => format!("data: {json}\n\n"),
            Err(RecvTimeoutError::Timeout) => ": keep-alive\n\n".to_string(),
            Err(RecvTimeoutError::Disconnected) => return,
        };
        // A write error means the tab closed; the hub prunes the sender when
        // this receiver drops.
        if writer.write_all(frame.as_bytes()).is_err() || writer.flush().is_err() {
            return;
        }
    }
}

fn route(
    state: &Arc<ServeState>,
    method: &Method,
    segments: &[&str],
    body: &str,
) -> (u16, Option<Value>) {
    // Reassembly completes on a timer, not on a request, so every request is
    // also a chance to sweep anything the receive thread could not finish.
    state.harvest();

    match (method, segments) {
        (Method::Get, ["api", "v1", "agent", "me"]) => (200, Some(agent_me(state))),

        (Method::Get, ["api", "v1", "agent", "peers"]) => (200, Some(agent_peers(state))),

        (Method::Get, ["api", "v1", "status"]) => (200, Some(status(state))),

        // ── UI queries ──────────────────────────────────────────────────
        (Method::Get, ["api", "v1", "messages"]) => {
            let messages = state.messages.lock().expect("message mutex poisoned");
            let rows: Vec<&MessageRecord> = messages.iter().collect();
            (200, Some(json!({ "data": rows })))
        }

        (Method::Get, ["api", "v1", "messages", id]) => {
            let messages = state.messages.lock().expect("message mutex poisoned");
            match messages.iter().find(|m| m.id == *id) {
                Some(m) => (200, Some(json!({ "data": m }))),
                None => (404, Some(json!({"error": format!("no message `{id}`")}))),
            }
        }

        (Method::Get, ["api", "v1", "relays"]) => (200, Some(relays(state))),

        (Method::Get, ["api", "v1", "stats"]) => (200, Some(stats(state))),

        (Method::Get, ["api", "v1", "events"]) => {
            let hub = state.events.lock().expect("event mutex poisoned");
            let events: Vec<Value> = hub
                .recent
                .iter()
                .filter_map(|e| serde_json::from_str(e).ok())
                .collect();
            (200, Some(json!({ "data": events })))
        }

        // Friendlier alias for the UI: the room lives in the body rather than
        // the path, since a messenger addresses a peer, not a chat id.
        (Method::Post, ["api", "v1", "messages"]) => {
            let parsed: Value = serde_json::from_str(body).unwrap_or(json!({}));
            let room = parsed
                .get("room")
                .and_then(Value::as_str)
                .unwrap_or("direct")
                .to_string();
            post_message(state, &room, body)
        }

        (Method::Post, ["api", "v1", "agent", "chats", room, "messages"]) => {
            post_message(state, room, body)
        }

        (Method::Get, ["api", "v1", "agent", "chats", _room, "messages", "next"]) => {
            match state.inbox.lock().expect("inbox mutex poisoned").pop() {
                Some(msg) => (
                    200,
                    Some(json!({"data": {
                        "id": msg.id,
                        "chat_room_id": msg.room,
                        "sender_id": msg.sender,
                        "content": msg.content,
                    }})),
                ),
                None => (204, None),
            }
        }

        (
            Method::Post,
            [
                "api",
                "v1",
                "agent",
                "chats",
                _room,
                "messages",
                id,
                state_name,
            ],
        ) if matches!(*state_name, "processing" | "processed") => {
            state
                .inbox
                .lock()
                .expect("inbox mutex poisoned")
                .ack(id, state_name);
            (200, Some(json!({"data": {"id": id, "state": state_name}})))
        }

        (Method::Get, ["api", "v1", "agent", "acks"]) => {
            let inbox = state.inbox.lock().expect("inbox mutex poisoned");
            let acks: Vec<Value> = inbox
                .acks
                .iter()
                .map(|(id, s)| json!({"id": id, "state": s}))
                .collect();
            (200, Some(json!({"data": acks})))
        }

        (Method::Post, ["api", "v1", "ratchet", "init"]) => {
            match RatchetClient::init(&state.home) {
                Ok((id, otk)) => (
                    200,
                    Some(json!({"data": {"identity": id, "one_time": otk}})),
                ),
                // An existing account is a refusal, not a retryable failure.
                Err(e) => (409, Some(json!({"error": e.to_string()}))),
            }
        }

        (Method::Post, ["api", "v1", "tokens", "issue"]) => {
            let parsed: Value = serde_json::from_str(body).unwrap_or(json!({}));
            let count = parsed
                .get("count")
                .and_then(Value::as_u64)
                .unwrap_or(credential::DEFAULT_BATCH_SIZE as u64) as usize;
            let pow_bits = parsed
                .get("pow_bits")
                .and_then(Value::as_u64)
                .unwrap_or(crate::pow::DEFAULT_POW_BITS as u64) as u32;
            let client_id = parsed
                .get("client_id")
                .and_then(Value::as_str)
                .unwrap_or("local-user");
            match token_issue(count, None, pow_bits, client_id, &state.home) {
                Ok(msg) => (200, Some(json!({"data": {"detail": msg}}))),
                Err(e) => (400, Some(json!({"error": format!("{e:#}")}))),
            }
        }

        _ => (404, Some(json!({"error": "not found"}))),
    }
}

fn agent_me(state: &Arc<ServeState>) -> Value {
    let identity = state.identity_hex();
    json!({"data": {
        "identity": identity,
        "delivery_addr": state.listen_addr,
        "tokens": state.token_count(),
    }})
}

fn agent_peers(state: &Arc<ServeState>) -> Value {
    let peers: Vec<Value> = state
        .config
        .peers
        .iter()
        .map(|(handle, peer)| json!({"handle": handle, "id": peer.id, "addr": peer.addr}))
        .collect();
    json!({ "data": peers })
}

fn status(state: &Arc<ServeState>) -> Value {
    let relays = state.config.relays.path();
    json!({"data": {
        "relays": relays,
        "directory_entries": state.list.entries.len(),
        "directory_attestations": state.list.attestations.len(),
        "directory_threshold": state.config.directory.threshold,
        "directory_keys": state.config.directory.keys.len(),
        "tokens": state.token_count(),
        "max_msg_len": MAX_MSG_LEN,
        // What a caller actually gets per packet: the body is hex-encoded on
        // the wire, so this is roughly half `max_msg_len`. Quoting the raw
        // Sphinx budget here would under-count packets, and therefore tokens.
        "packet_payload_bytes": packet_payload_bytes("direct"),
    }})
}

/// The relay directory as the UI shows it: every claim in the signed list,
/// with the three this client actually routes through marked by role.
fn relays(state: &Arc<ServeState>) -> Value {
    let path = state.config.relays.path();
    let role_of = |addr: &str| -> Option<&'static str> {
        path.iter()
            .position(|p| *p == addr)
            .map(|i| ["entry", "middle", "exit"][i])
    };
    let entries: Vec<Value> = state
        .list
        .entries
        .iter()
        .map(|claim| {
            let role = role_of(&claim.address);
            json!({
                "address": claim.address,
                "identity_key": hex::encode(claim.identity_pubkey),
                "sphinx_key": hex::encode(claim.sphinx_pubkey),
                "role": role,
                // Every entry in a loaded list has already had its
                // self-signature verified — an unsigned one refuses the load.
                "status": if role.is_some() { "IN_PATH" } else { "AVAILABLE" },
            })
        })
        .collect();
    json!({"data": {
        "entries": entries,
        "attestations": state.list.attestations.len(),
        "threshold": state.config.directory.threshold,
        "signers": state.config.directory.keys.len(),
        "policy_enforced": !state.config.directory.keys.is_empty(),
    }})
}

/// Counts for the header tiles. Derived from the live window, not persisted.
fn stats(state: &Arc<ServeState>) -> Value {
    let messages = state.messages.lock().expect("message mutex poisoned");
    let mut by_state: HashMap<&str, usize> = HashMap::new();
    let mut sent = 0usize;
    let mut received = 0usize;
    let mut tokens_spent = 0u32;
    let mut bytes = 0usize;
    for m in messages.iter() {
        *by_state.entry(m.state).or_default() += 1;
        match m.direction {
            "sent" => sent += 1,
            _ => received += 1,
        }
        tokens_spent += m.tokens_spent;
        bytes += m.bytes;
    }
    json!({"data": {
        "total_messages": messages.len(),
        "by_state": by_state,
        "sent": sent,
        "received": received,
        "bytes": bytes,
        "tokens_spent": tokens_spent,
        "tokens_remaining": state.token_count(),
        "relays_in_path": state.config.relays.path().len(),
        "directory_entries": state.list.entries.len(),
    }})
}

fn post_message(state: &Arc<ServeState>, room: &str, body: &str) -> (u16, Option<Value>) {
    let parsed: Value = match serde_json::from_str(body) {
        Ok(v) => v,
        Err(e) => {
            return (
                400,
                Some(json!({"error": format!("invalid JSON body: {e}")})),
            );
        }
    };
    let Some(content) = parsed.get("content").and_then(Value::as_str) else {
        return (400, Some(json!({"error": "missing `content`"})));
    };
    let Some(peer) = parsed.get("peer").and_then(Value::as_str) else {
        return (400, Some(json!({"error": "missing `peer`"})));
    };

    match state.send_message(room, peer, content) {
        Ok(id) => (200, Some(json!({"data": {"id": id}}))),
        // Out of tokens, unknown peer and a refused path are all caller-side
        // problems: report them as 4xx so the client does not retry blindly.
        Err(e) => (409, Some(json!({"error": format!("{e:#}")}))),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn frame(id: &str, c: u64, s: u32, n: u32, room: &str, d: &str) -> WireFrame {
        WireFrame {
            m: id.into(),
            c,
            s,
            n,
            r: room.into(),
            d: d.into(),
        }
    }

    #[test]
    fn the_reported_packet_budget_matches_what_send_actually_does() {
        // The UI multiplies this number to predict how many admission tokens a
        // message will cost, so a mismatch is a lie about price.
        let budget = packet_payload_bytes("direct");
        assert!(budget > 0);

        let exact = "x".repeat(budget);
        assert_eq!(
            build_frames("wb-00000000-0000000000000000-0", 0, "direct", &exact)
                .unwrap()
                .len(),
            1,
            "a body of exactly the reported budget must fit in one packet"
        );

        let over = "x".repeat(budget + 1);
        assert_eq!(
            build_frames("wb-00000000-0000000000000000-0", 0, "direct", &over)
                .unwrap()
                .len(),
            2,
            "one byte more must cost a second packet"
        );
    }

    #[test]
    fn frames_fit_inside_the_sphinx_payload_budget() {
        let body = "x".repeat(8_000);
        let frames = build_frames("wb-abc", 7, "surveillance", &body).unwrap();
        assert!(frames.len() > 1, "an 8 KB body must span several packets");
        for f in &frames {
            let wire = serde_json::to_string(f).unwrap();
            assert!(
                wire.len() <= MAX_MSG_LEN,
                "frame of {} B exceeds the {MAX_MSG_LEN} B plaintext budget",
                wire.len()
            );
        }
    }

    #[test]
    fn reassembly_is_byte_exact_including_non_ascii() {
        let body = "événement \"quoted\" {\"json\":true} 🎯".repeat(60);
        let frames = build_frames("wb-1", 0, "room-1", &body).unwrap();
        let mut inbox = Inbox::default();
        for f in frames {
            inbox.accept("sender-a".into(), f);
        }
        age_out(&mut inbox);
        let got = inbox.pop().expect("message must be released");
        assert_eq!(got.content, body);
        assert_eq!(got.id, "wb-1");
        assert_eq!(got.room, "room-1");
        assert_eq!(got.sender, "sender-a");
        assert!(inbox.pop().is_none(), "queue must drain to empty");
    }

    #[test]
    fn empty_body_round_trips_as_a_single_frame() {
        let frames = build_frames("wb-empty", 0, "room-1", "").unwrap();
        assert_eq!(frames.len(), 1);
        let mut inbox = Inbox::default();
        inbox.accept("sender-a".into(), frames[0].clone());
        age_out(&mut inbox);
        assert_eq!(inbox.pop().unwrap().content, "");
    }

    /// Pretend every held message has already waited out the reorder window,
    /// so the release rules can be exercised without sleeping.
    fn age_out(inbox: &mut Inbox) {
        let past = Instant::now() - REORDER_WINDOW - Duration::from_millis(1);
        for (_, _, at) in inbox.holding.iter_mut() {
            *at = past;
        }
    }

    fn deliver(inbox: &mut Inbox, sender: &str, id: &str, counter: u64, body: &str) {
        for chunk in build_frames(id, counter, "room-1", body).unwrap() {
            inbox.accept(sender.into(), chunk);
        }
    }

    fn drain(inbox: &mut Inbox) -> Vec<String> {
        std::iter::from_fn(|| inbox.pop())
            .map(|r| r.content)
            .collect()
    }

    #[test]
    fn out_of_order_chunks_reassemble() {
        let body = "y".repeat(4_000);
        let mut frames = build_frames("wb-2", 0, "room-1", &body).unwrap();
        frames.reverse();
        let mut inbox = Inbox::default();
        for f in frames {
            inbox.accept("sender-a".into(), f);
        }
        age_out(&mut inbox);
        assert_eq!(inbox.pop().unwrap().content, body);
    }

    #[test]
    fn messages_are_released_in_send_order_despite_mix_reordering() {
        let mut inbox = Inbox::default();
        // Arrive 1, 2, 0 — the order a mixnet may well produce. All three
        // land inside the reorder window, so send order is fully recovered.
        deliver(&mut inbox, "sender-a", "m-1", 1, "m-1");
        deliver(&mut inbox, "sender-a", "m-2", 2, "m-2");
        deliver(&mut inbox, "sender-a", "m-0", 0, "m-0");
        assert!(
            inbox.pop().is_none(),
            "nothing may be released while the window is still open"
        );

        age_out(&mut inbox);
        assert_eq!(drain(&mut inbox), vec!["m-0", "m-1", "m-2"]);
    }

    #[test]
    fn a_lost_message_does_not_stall_its_successors_forever() {
        let mut inbox = Inbox::default();
        // Counter 0 never arrives; 1 and 2 must still be released once the
        // reorder window lapses.
        deliver(&mut inbox, "sender-a", "m-1", 1, "m-1");
        deliver(&mut inbox, "sender-a", "m-2", 2, "m-2");
        assert!(inbox.pop().is_none(), "held while the window is open");

        age_out(&mut inbox);
        assert_eq!(drain(&mut inbox), vec!["m-1", "m-2"]);
    }

    #[test]
    fn a_late_message_is_handed_over_rather_than_stranded() {
        let mut inbox = Inbox::default();
        deliver(&mut inbox, "sender-a", "m-1", 1, "m-1");
        age_out(&mut inbox);
        assert_eq!(drain(&mut inbox), vec!["m-1"]);

        // Counter 0 turns up after we already moved past it — out of order,
        // but delivered rather than dropped.
        deliver(&mut inbox, "sender-a", "m-0", 0, "m-0");
        assert_eq!(drain(&mut inbox), vec!["m-0"]);
    }

    #[test]
    fn independent_senders_do_not_block_each_other() {
        let mut inbox = Inbox::default();
        deliver(&mut inbox, "sender-a", "a-0", 0, "a-0");
        // Sender B's counter space is its own: starting at 5 must not make it
        // wait for counters 0..4, which belong to nobody.
        deliver(&mut inbox, "sender-b", "b-5", 5, "b-5");
        age_out(&mut inbox);
        assert_eq!(drain(&mut inbox), vec!["a-0", "b-5"]);

        // Once each sender has a baseline, their next message flows straight
        // through with no window wait.
        deliver(&mut inbox, "sender-b", "b-6", 6, "b-6");
        deliver(&mut inbox, "sender-a", "a-1", 1, "a-1");
        assert_eq!(drain(&mut inbox), vec!["b-6", "a-1"]);
    }

    #[test]
    fn malformed_frames_are_dropped_not_buffered() {
        let mut inbox = Inbox::default();
        inbox.accept("sender-a".into(), frame("bad", 0, 3, 0, "room-1", "00"));
        inbox.accept("sender-a".into(), frame("bad", 0, 5, 2, "room-1", "00"));
        inbox.accept("sender-a".into(), frame("bad2", 0, 0, 1, "room-1", "zz"));
        assert!(inbox.pop().is_none());
        assert!(inbox.partial.is_empty() || !inbox.partial.contains_key("bad"));
    }

    #[test]
    fn loopback_check_rejects_external_addresses() {
        assert!(require_loopback("127.0.0.1:9001").is_ok());
        assert!(require_loopback("[::1]:9001").is_ok());
        assert!(require_loopback("0.0.0.0:9001").is_err());
        assert!(require_loopback("192.168.1.5:9001").is_err());
        assert!(require_loopback("not-an-address").is_err());
    }
}
